language: python
cache: pip

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.11
    - python: 3.10
    - python: 3.9
    - python: 3.8
    - python: 3.7
    - python: pypy3

install:
 - pip install -U pip
 - pip install -U tox-travis

script:
 - tox
